TRAIN:
  BASE_DATA_PATH: "C://Users//acer//Downloads//birdclef-2024"
  TRAIN_METADATA_FILENAME: "train_metadata.csv"
  TRAIN_AUDIODATA_FILENAME: "train_audio"
  SAMPLE_RATE: 32000
  HOP_SIZE: 512
  N_FFT: 2028
  FRAME_SIZE: 2048
  N_MELS: 224
  FIXED_AUDIO_DURATION: 15
  F_MIN: 20
  F_MAX: 18000
  IMG_SIZE: [224, 224]
  SEED: 42
  N_MFCC: 40
  IS_DECODER_ACTIVATED: TRUE
  IS_AUGMENTATION_ACTIVATED: TRUE
  IS_AUGMENTATION_ACTIVATED_FOR_DIFFERENT_AUGMENTATION: TRUE
  BATCH_SIZE: 64
  EPOCHS: 20

EDA:
  IS_ACTIVATED_FOR_METADATA: False
  IS_ACTIVATED_FOR_AUDIO: False

SAVED_DATA:
  OUTPUT_FILENAME_WITHOUT_AUG: "mfcc_data"
  OUTPUT_FILENAME_WITH_AUG:
    TRAIN: "output_mfcc_train"
    VALID: "output_mfcc_valid"
  OUTPUT_FILENAME_WITH_DIFFERENT_AUG:
    TRAIN: "output_mfcc_newaug_train"
    VALID: "output_mfcc_newaug_valid"
